environment:
  matrix:
    # - PYTHON: C:\Python39-x64
    - PYTHON: C:\Python38-x64
    # - PYTHON: C:\Python37-x64
    # - PYTHON: C:\Python36-x64

init:
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - SET PYTHONIOENCODING=utf-8

branches:
  only:
    - master

build: false

test_script:
  - .\scripts\build.bat

artifacts:
  - path: dist/lncrawl.exe
    name: lncrawl

cache:
  - '%LOCALAPPDATA%\pip\Cache'
