os: linux
dist: xenial
language: python
python:
  - "3.7"
  - "3.6"
  - "3.5"
  - nightly
  - pypy3.5-6.0

matrix:
  allow_failures:
    - python: nightly
    - python: pypy3.5-6.0
    - os: osx
  fast_finish: true

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew upgrade python
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - pip install -r requirements.txt

script:
  - python __main__.py --bot test

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

branches:
  only:
    - master

notifications:
  email: false
