os: linux
dist: xenial
language: python
python:
  - "3.8"
  - "3.7"
  - "3.6"
  - "3.5"
  - nightly

matrix:
  allow_failures:
    - python: nightly
    - os: osx
  fast_finish: true

before_install:
  - |
    if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
      brew upgrade python
      export PATH="/usr/local/opt/python/libexec/bin:${PATH}"
    fi
install:
  - pip install -r requirements.txt
  - pip install flake8

before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

script:
  - python __main__.py --bot test -lll

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

branches:
  only:
    - master

notifications:
  email: false
