name: Generate source index

on:
  push:
    branches:
      - dev
    paths:
      - "sources/**"
      - "!sources/_index.json"
      - "scripts/index_gen.py"

jobs:
  index_gen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
  
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements-app.txt
 
      - name: Generate index
        run: python ./scripts/index_gen.py
 
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
