name: Lint pull requests

on:
  pull_request:
    branches:
      - master

jobs:
  lint_test:
    name: Lint & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel setuptools
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --count --show-source --statistics

      - name: Build wheel
        run: python setup.py clean bdist_wheel

      - name: Install and test the wheel package
        run: |
          pip install dist/lightnovel_crawler*.whl
          lncrawl --list-sources
